/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRafflesRouteImport } from './routes/about-raffles'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ConciergeRouteImport } from './routes/concierge'
import { Route as ConciergeDeskRouteImport } from './routes/concierge-desk'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ForYouRouteImport } from './routes/for-you'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as GratitudeRouteImport } from './routes/gratitude'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HotelBridgeRouteImport } from './routes/hotel-bridge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PressRouteImport } from './routes/press'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SalesAndLeasingRouteImport } from './routes/sales-and-leasing'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StaffDashboardRouteImport } from './routes/staff-dashboard'
import { Route as StaffSigninRouteImport } from './routes/staff-signin'
import { Route as StaffSignupRouteImport } from './routes/staff-signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as HealthReadyRouteImport } from './routes/health.ready'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRafflesRoute = AboutRafflesRouteImport.update({
  id: '/about-raffles',
  path: '/about-raffles',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeRoute = ConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeDeskRoute = ConciergeDeskRouteImport.update({
  id: '/concierge-desk',
  path: '/concierge-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ForYouRoute = ForYouRouteImport.update({
  id: '/for-you',
  path: '/for-you',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const GratitudeRoute = GratitudeRouteImport.update({
  id: '/gratitude',
  path: '/gratitude',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelBridgeRoute = HotelBridgeRouteImport.update({
  id: '/hotel-bridge',
  path: '/hotel-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesAndLeasingRoute = SalesAndLeasingRouteImport.update({
  id: '/sales-and-leasing',
  path: '/sales-and-leasing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/staff-dashboard',
  path: '/staff-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSigninRoute = StaffSigninRouteImport.update({
  id: '/staff-signin',
  path: '/staff-signin',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSignupRoute = StaffSignupRouteImport.update({
  id: '/staff-signup',
  path: '/staff-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthReadyRoute = HealthReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => HealthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-raffles': typeof AboutRafflesRoute
  '/account': typeof AccountRoute
  '/amenities': typeof AmenitiesRoute
  '/community': typeof CommunityRoute
  '/concierge': typeof ConciergeRoute
  '/concierge-desk': typeof ConciergeDeskRoute
  '/directory': typeof DirectoryRoute
  '/events': typeof EventsRoute
  '/for-you': typeof ForYouRoute
  '/gallery': typeof GalleryRoute
  '/governance': typeof GovernanceRoute
  '/gratitude': typeof GratitudeRoute
  '/health': typeof HealthRouteWithChildren
  '/hotel-bridge': typeof HotelBridgeRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/proposals': typeof ProposalsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales-and-leasing': typeof SalesAndLeasingRoute
  '/services': typeof ServicesRoute
  '/staff-dashboard': typeof StaffDashboardRoute
  '/staff-signin': typeof StaffSigninRoute
  '/staff-signup': typeof StaffSignupRoute
  '/terms': typeof TermsRoute
  '/health/ready': typeof HealthReadyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-raffles': typeof AboutRafflesRoute
  '/account': typeof AccountRoute
  '/amenities': typeof AmenitiesRoute
  '/community': typeof CommunityRoute
  '/concierge': typeof ConciergeRoute
  '/concierge-desk': typeof ConciergeDeskRoute
  '/directory': typeof DirectoryRoute
  '/events': typeof EventsRoute
  '/for-you': typeof ForYouRoute
  '/gallery': typeof GalleryRoute
  '/governance': typeof GovernanceRoute
  '/gratitude': typeof GratitudeRoute
  '/health': typeof HealthRouteWithChildren
  '/hotel-bridge': typeof HotelBridgeRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/proposals': typeof ProposalsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales-and-leasing': typeof SalesAndLeasingRoute
  '/services': typeof ServicesRoute
  '/staff-dashboard': typeof StaffDashboardRoute
  '/staff-signin': typeof StaffSigninRoute
  '/staff-signup': typeof StaffSignupRoute
  '/terms': typeof TermsRoute
  '/health/ready': typeof HealthReadyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-raffles': typeof AboutRafflesRoute
  '/account': typeof AccountRoute
  '/amenities': typeof AmenitiesRoute
  '/community': typeof CommunityRoute
  '/concierge': typeof ConciergeRoute
  '/concierge-desk': typeof ConciergeDeskRoute
  '/directory': typeof DirectoryRoute
  '/events': typeof EventsRoute
  '/for-you': typeof ForYouRoute
  '/gallery': typeof GalleryRoute
  '/governance': typeof GovernanceRoute
  '/gratitude': typeof GratitudeRoute
  '/health': typeof HealthRouteWithChildren
  '/hotel-bridge': typeof HotelBridgeRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/proposals': typeof ProposalsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales-and-leasing': typeof SalesAndLeasingRoute
  '/services': typeof ServicesRoute
  '/staff-dashboard': typeof StaffDashboardRoute
  '/staff-signin': typeof StaffSigninRoute
  '/staff-signup': typeof StaffSignupRoute
  '/terms': typeof TermsRoute
  '/health/ready': typeof HealthReadyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-raffles'
    | '/account'
    | '/amenities'
    | '/community'
    | '/concierge'
    | '/concierge-desk'
    | '/directory'
    | '/events'
    | '/for-you'
    | '/gallery'
    | '/governance'
    | '/gratitude'
    | '/health'
    | '/hotel-bridge'
    | '/login'
    | '/management'
    | '/marketplace'
    | '/messages'
    | '/press'
    | '/privacy'
    | '/proposals'
    | '/reset-password'
    | '/sales-and-leasing'
    | '/services'
    | '/staff-dashboard'
    | '/staff-signin'
    | '/staff-signup'
    | '/terms'
    | '/health/ready'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-raffles'
    | '/account'
    | '/amenities'
    | '/community'
    | '/concierge'
    | '/concierge-desk'
    | '/directory'
    | '/events'
    | '/for-you'
    | '/gallery'
    | '/governance'
    | '/gratitude'
    | '/health'
    | '/hotel-bridge'
    | '/login'
    | '/management'
    | '/marketplace'
    | '/messages'
    | '/press'
    | '/privacy'
    | '/proposals'
    | '/reset-password'
    | '/sales-and-leasing'
    | '/services'
    | '/staff-dashboard'
    | '/staff-signin'
    | '/staff-signup'
    | '/terms'
    | '/health/ready'
  id:
    | '__root__'
    | '/'
    | '/about-raffles'
    | '/account'
    | '/amenities'
    | '/community'
    | '/concierge'
    | '/concierge-desk'
    | '/directory'
    | '/events'
    | '/for-you'
    | '/gallery'
    | '/governance'
    | '/gratitude'
    | '/health'
    | '/hotel-bridge'
    | '/login'
    | '/management'
    | '/marketplace'
    | '/messages'
    | '/press'
    | '/privacy'
    | '/proposals'
    | '/reset-password'
    | '/sales-and-leasing'
    | '/services'
    | '/staff-dashboard'
    | '/staff-signin'
    | '/staff-signup'
    | '/terms'
    | '/health/ready'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRafflesRoute: typeof AboutRafflesRoute
  AccountRoute: typeof AccountRoute
  AmenitiesRoute: typeof AmenitiesRoute
  CommunityRoute: typeof CommunityRoute
  ConciergeRoute: typeof ConciergeRoute
  ConciergeDeskRoute: typeof ConciergeDeskRoute
  DirectoryRoute: typeof DirectoryRoute
  EventsRoute: typeof EventsRoute
  ForYouRoute: typeof ForYouRoute
  GalleryRoute: typeof GalleryRoute
  GovernanceRoute: typeof GovernanceRoute
  GratitudeRoute: typeof GratitudeRoute
  HealthRoute: typeof HealthRouteWithChildren
  HotelBridgeRoute: typeof HotelBridgeRoute
  LoginRoute: typeof LoginRoute
  ManagementRoute: typeof ManagementRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MessagesRoute: typeof MessagesRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  ProposalsRoute: typeof ProposalsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SalesAndLeasingRoute: typeof SalesAndLeasingRoute
  ServicesRoute: typeof ServicesRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffSigninRoute: typeof StaffSigninRoute
  StaffSignupRoute: typeof StaffSignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-raffles': {
      id: '/about-raffles'
      path: '/about-raffles'
      fullPath: '/about-raffles'
      preLoaderRoute: typeof AboutRafflesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge': {
      id: '/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof ConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge-desk': {
      id: '/concierge-desk'
      path: '/concierge-desk'
      fullPath: '/concierge-desk'
      preLoaderRoute: typeof ConciergeDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-you': {
      id: '/for-you'
      path: '/for-you'
      fullPath: '/for-you'
      preLoaderRoute: typeof ForYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gratitude': {
      id: '/gratitude'
      path: '/gratitude'
      fullPath: '/gratitude'
      preLoaderRoute: typeof GratitudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-bridge': {
      id: '/hotel-bridge'
      path: '/hotel-bridge'
      fullPath: '/hotel-bridge'
      preLoaderRoute: typeof HotelBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-and-leasing': {
      id: '/sales-and-leasing'
      path: '/sales-and-leasing'
      fullPath: '/sales-and-leasing'
      preLoaderRoute: typeof SalesAndLeasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-dashboard': {
      id: '/staff-dashboard'
      path: '/staff-dashboard'
      fullPath: '/staff-dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-signin': {
      id: '/staff-signin'
      path: '/staff-signin'
      fullPath: '/staff-signin'
      preLoaderRoute: typeof StaffSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-signup': {
      id: '/staff-signup'
      path: '/staff-signup'
      fullPath: '/staff-signup'
      preLoaderRoute: typeof StaffSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/ready': {
      id: '/health/ready'
      path: '/ready'
      fullPath: '/health/ready'
      preLoaderRoute: typeof HealthReadyRouteImport
      parentRoute: typeof HealthRoute
    }
  }
}

interface HealthRouteChildren {
  HealthReadyRoute: typeof HealthReadyRoute
}

const HealthRouteChildren: HealthRouteChildren = {
  HealthReadyRoute: HealthReadyRoute,
}

const HealthRouteWithChildren =
  HealthRoute._addFileChildren(HealthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRafflesRoute: AboutRafflesRoute,
  AccountRoute: AccountRoute,
  AmenitiesRoute: AmenitiesRoute,
  CommunityRoute: CommunityRoute,
  ConciergeRoute: ConciergeRoute,
  ConciergeDeskRoute: ConciergeDeskRoute,
  DirectoryRoute: DirectoryRoute,
  EventsRoute: EventsRoute,
  ForYouRoute: ForYouRoute,
  GalleryRoute: GalleryRoute,
  GovernanceRoute: GovernanceRoute,
  GratitudeRoute: GratitudeRoute,
  HealthRoute: HealthRouteWithChildren,
  HotelBridgeRoute: HotelBridgeRoute,
  LoginRoute: LoginRoute,
  ManagementRoute: ManagementRoute,
  MarketplaceRoute: MarketplaceRoute,
  MessagesRoute: MessagesRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  ProposalsRoute: ProposalsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SalesAndLeasingRoute: SalesAndLeasingRoute,
  ServicesRoute: ServicesRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffSigninRoute: StaffSigninRoute,
  StaffSignupRoute: StaffSignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
